admin/views/plugins.php, install.php, languages/fr_FR.json, plugins/pages/language/en_US.json, plugins/pages/language/fr_FR.json, plugins/pages/plugin.php
Plugin page:
* Add label for display in theme
* Add french lang pack
* Add label in install.php
Update french lang pack
Add a space in Plugin name and version
=> More change

plugins/disqus/languages/de_DE.json, plugins/opengraph/languages/de_DE.json, plugins/simplemde/languages/de_DE.json, plugins/tags/languages/de_DE.json
All language files for plugins now in UTF-8.
=> New translations and small corrections

languages/pl_PL.json
=> Dashboard clean-up

languages/he_IL.json
Updated string that caused the file to malfunction and not show up.
=> Updated string

languages/it_IT.json
=> Update to version 0.7

languages/it_IT.json
New Bludit Images system v8 and Cover image.
Fix missing comma and translation improvements.
=> New Bludit Images system v8 and Cover image

bl-languages/ms_MY.json
Fixed advanced and images tabs not showing when creating post or pages.
=> Update: ms_MY

.htaccess
Deny access to bl-content directory txt files instead of content directory txt files.
=> Fix Security issue

bl-plugins/about/languages/tr_TR.json, bl-plugins/disqus/languages/tr_TR.json, bl-plugins/googletools/languages/tr_TR.json, bl-plugins/maintancemode/languages/tr_TR.json, bl-plugins/pages/languages/tr_TR.json, bl-plugins/simplemde/languages/tr_TR.json, bl-plugins/tags/languages/tr_TR.json
Fix Turkish language files of some plugins.
=> New push request

bl-plugins/api/plugin.php
=> Corrected typo post to page.

bl-kernel/admin/views/settings-regional.php, bl-languages/fi_FI.json, bl-languages/ms_MY.json
I have checked and replaced all occurrences of the misspelled translation key. 
The keys in every other translation were already fixed..
=> Fixed typo in translation. Fixes #294

bl-kernel/admin/themes/default/init.php, bl-kernel/dbpages.class.php, bl-kernel/js/bludit-cover-image.js, bl-kernel/js/bludit-images-v8.js
I'm sorry, but I had to create a new request :(
I fucked up my branch, will not happen again..
=> Fixed PHP notice after installation and javascript translations

install.php
=> added PHP GD module to required modules.

bl-languages/pl_PL.json
=> Polish language pack updated

bl-plugins/about/plugin.php
Just to allow us to use HTML in the about section.
=> Decode HTML entities

bl-kernel/admin/themes/default/init.php, bl-kernel/ajax/uploader.php
Just to make #222 able to merge again
=> Added SVG image support for uploads

bl-themes/log/assets/css/bludit.css, bl-themes/log/assets/css/ie8.css
This PR provides fix for issue #287
=> Responsive images for 'log' default theme

bl-languages/fr_FR.json
=> Corrige une faute

bl-plugins/simplemde/languages/en_US.json, bl-plugins/simplemde/plugin.php
=> Add Spell Checker Option in SimpleMDE Plugin

bl-kernel/helpers/paginator.class.php, bl-languages/en_US.json, bl-themes/log/assets/css/main.css, bl-themes/log/php/home.php
I added urlFirstPage() and urlLastPage() to the paginator class.
In addition I implemented this in the log theme, where the buttons are showed as soon as there is a previous / next page.
=> [req171] added first / last page for paginator

bl-kernel/admin/themes/default/css/default.css, bl-kernel/admin/views/manage-posts.php
Implementation with first / last page for Manage > Posts in the admin area.
The navigation appears as soon as "Previous / Next page" is visible.
=> [req171] First / Last page for admin area

bl-languages/it_IT.json
Hello,
This is the pull request for updating italian translation.
Keep the nice job!
=> Update Italian translation

bl-languages/en_US.json, bl-languages/es_AR.json, bl-plugins/simplemde/languages/de_CH.json, bl-plugins/simplemde/languages/de_DE.json, bl-plugins/simplemde/languages/en_US.json, bl-plugins/simplemde/languages/es_AR.json
Moved to plugin language file, addition of German translation.
=> Phrase "content-here-supports-markdown-and-html-code"

bl-languages/it_IT.json
=> Correction of typo

bl-themes/lingonberry/css/bludit.css, bl-themes/lingonberry/index.php, bl-themes/lingonberry/php/head.php, bl-themes/lingonberry/php/home.php, bl-themes/lingonberry/php/post.php, bl-themes/lingonberry/php/sidebar.php
Should be fully usable now.
Plugins not tested.
Sitebar plugins will never work as before. (Not included in the theme.)
=> More Lingonberry updates.

bl-plugins/simplemde/plugin.php
A simple addition to the plugin's toolbar. I feel that the pagebreak function needs to be more noticeable by the users. Improvements are welcome.
=> Added pagebreak button to SimpleMDE

bl-plugins/simplemde/languages/de_CH.json, bl-plugins/simplemde/languages/de_DE.json, bl-plugins/simplemde/languages/en.json, bl-plugins/simplemde/languages/es.json, bl-plugins/simplemde/plugin.php
Translation for "Content here supports Markdown and HTML code".
=> Adding translation to plugin SimpleMDE

bl-plugins/disqus/languages/en.json, bl-plugins/disqus/languages/ru_RU.json, bl-plugins/disqus/plugin.php, bl-plugins/simplemde/languages/ru_RU.json, bl-plugins/simplemde/plugin.php
Added possibility to choose where on site comments will be aviable as it was in v1.x
=> Disqus plugin update

bl-kernel/admin/themes/default/css/default.css
Hopefully to solve #401 and #539
=> Show Edit page Sidebar below all else in Mobile View

bl-kernel/helpers/filesystem.class.php
=> filesystem.class.php update for PHP 7.2 compatibility

bl-kernel/helpers/text.class.php
=> text.class.php update for PHP 7.2 compatibility

bl-plugins/google/plugin.php
Fixed Google HTML verification and tag displaying
=> Update Google plugin

bl-themes/blogx/php/home.php, bl-themes/blogx/php/page.php
Fix https://github.com/bludit/bludit/issues/662
=> Add pageBegin and pageEnd hooks to blogx

bl-languages/it_IT.json, bl-plugins/about/languages/it.json, bl-plugins/api/languages/it.json, bl-plugins/backup/languages/it.json, bl-plugins/categories/languages/it.json, bl-plugins/disqus/languages/it.json, bl-plugins/google/languages/it.json, bl-plugins/html-code/languages/it.json, bl-plugins/links/languages/it.json, bl-plugins/maintenance-mode/languages/it.json, bl-plugins/navigation/languages/it.json, bl-plugins/opengraph/languages/it.json, bl-plugins/rss/languages/it.json, bl-plugins/simplemde/languages/en.json, bl-plugins/sitemap/languages/it.json, bl-plugins/static-pages/languages/it.json, bl-plugins/tags/languages/it.json, bl-plugins/tinymce/languages/it.json, bl-plugins/twitter-cards/languages/it.json, bl-plugins/version/languages/it.json, bl-themes/alternative/languages/it.json, bl-themes/blogx/languages/en.json
Completed the italian translation
=> Italian Translation

bl-kernel/dbusers.class.php
https://github.com/bludit/bludit/issues/683
=> Fix disable user option

bl-plugins/simple-stats/plugin.php
Fix https://github.com/bludit/bludit/issues/729
=> Fix floats bug

bl-kernel/site.class.php
https://github.com/bludit/bludit/issues/771
=> Fix admin filter bug

bl-plugins/robots/languages/de_CH.json, bl-plugins/robots/languages/de_DE.json
fix the quotes problem in German translations
=> fix quotes in German translations

bl-languages/ru_RU.json
Well, let me know, if you will add new strings. Ok?
=> Translated new strings

bl-plugins/search/vendors/fuzz.php
Fixes the search issue described in #889
=> Remove Static Declarations

bl-kernel/boot/init.php
https://github.com/bludit/bludit/issues/902
=> Remove deprecated track_errors

bl-plugins/backup/languages/it.json, bl-plugins/canonical/languages/it.json, bl-plugins/disqus/languages/it.json, bl-plugins/hit-counter/languages/it.json, bl-plugins/opengraph/languages/it.json, bl-plugins/remote-content/languages/it.json, bl-plugins/robots/languages/it.json, bl-plugins/search/languages/it.json, bl-plugins/simple-stats/languages/it.json
Updated the italian translation and translated the plugins:
* Canonical
* Hit-counter
* Remote-content
* Robots
* Search
* Simple-stats
=> Italian translations

bl-plugins/rss/plugin.php
Added ```static``` and ```sticky``` pages to Bludit RSS ```plugin.php```
=> RSS plugin.php update

bl-kernel/admin/views/edit-content.php
Data changes on 2nd or 3rd save.
Try
```
abc </textarea> def
```
OR
```
<code>
&lt;p&gt; test &lt;/p&gt;
</code>
```
=> Bug Fix #1032

bl-languages/de_DE.json
Translation of "author-can-write-and-edit-their-own-content"
=> Minor Changes in de_DE.json

bl-plugins/rss/plugin.php
1. Declare Atom schema support
2. Escape international characters in URL
3. Ignore locale in date
=> Harmonize RSS feed with W3C recommendations

bl-languages/ru_RU.json
You added the string "view" but not added "edit" from the same part of code. Also, the status of any pages from _**smart search**_ can't be translated cuz u again not added it.
**Sorry that I was absent for a long time**
=> Translated new strings to Russian

bl-kernel/admin/views/dashboard.php
More info: https://select2.org/troubleshooting/common-problems
=> Fix #1135 clippy input on mobile dropdown menu bug

bl-kernel/helpers/theme.class.php
In my testing this has improved my Page Insights score pretty significantly especially for mobile. See: https://web.dev/render-blocking-resources/
=> Add the "async" parameter to script tags

bl-plugins/version/plugin.php
Please check it. I tested on my site and it's working perfectly, but maybe I did some mistakes.
=> Trying to add tanslatable string

bl-plugins/remote-content/languages/ru_RU.json
=> Translation improved

bl-plugins/about/languages/da.json, bl-plugins/api/languages/da.json, bl-plugins/backup/languages/da.json, bl-plugins/canonical/languages/da.json, bl-plugins/categories/languages/da.json, bl-plugins/custom-fields-parser/languages/da.json, bl-plugins/disqus/languages/da.json, bl-plugins/easymde/languages/da.json, bl-plugins/hit-counter/languages/da.json, bl-plugins/html-code/languages/da.json, bl-plugins/links/languages/da.json, bl-plugins/maintenance-mode/languages/da.json, bl-plugins/navigation/languages/da.json, bl-plugins/opengraph/languages/da.json, bl-plugins/remote-content/languages/da.json, bl-plugins/robots/languages/da.json, bl-plugins/rss/languages/da.json, bl-plugins/search/languages/da.json, bl-plugins/simple-stats/languages/da.json, bl-plugins/sitemap/languages/da.json, bl-plugins/static-pages/languages/da.json, bl-plugins/tags/languages/da.json, bl-plugins/tinymce/languages/da.json, bl-plugins/twitter-cards/languages/da.json, bl-plugins/version/languages/da.json
Danish translations for core plugins
=> Core plugin language da.json

bl-kernel/ajax/upload-images.php
Hellow,
this is a fix for issue #1176.
Sincerely,
Sam.
=> [BUGFIX] AJAX Error Message when uploading Images

bl-kernel/abstract/plugin.class.php, bl-kernel/admin/themes/booty/html/alert.php, bl-kernel/boot/variables.php, bl-kernel/functions.php, bl-kernel/login.class.php, bl-kernel/syslog.class.php, bl-kernel/url.class.php
I found a couple of typos while browsing the source code. Thought I would create a pull request to familiarize myself with the process and make a small contribution to this great CMS.
=> Correct small typos

bl-plugins/backup/plugin.php
Hellow,
this pull request fixes the vulnerability described in #1218, by storing the MD5 checksum of the Backup archive to an own file called `.BLUDIT_BACKUP` (in the root directory of the zip).
~ Sam.
PS.: Of course, this isn't the best solution, since you're still able to add a regenerated MD5 checksum file to the archive. But to be serious... administrators should also pay attention to such things in general.
=> Validate Backup Files

bl-kernel/admin/views/login.php
Hey,
Hope you are doing well and good.
I took my spare time to look on the issue #1254 .I was able to implement a fix on the issue. 
Cheers,
Tibin
=> Fix for /issues/1254

bl-plugins/rss/plugin.php
Link for image is very important for sharing rss.
=> Added link for image

bl-plugins/latest-pages/languages/de_AT.json, bl-plugins/latest-pages/languages/de_CH.json, bl-plugins/latest-pages/languages/de_DE.json, bl-plugins/latest-pages/languages/en.json, bl-plugins/latest-pages/plugin.php
Additon for translations, translations.
=> V4.0 plugin Latest pages

bl-plugins/welcome/languages/de_AT.json, bl-plugins/welcome/languages/de_CH.json, bl-plugins/welcome/languages/de_DE.json, bl-plugins/welcome/languages/en.json, bl-plugins/welcome/plugin.php
- Modification of the code from line 23 to add translation for "Welcome".
- Translations
=> V4.0 plugin Welcome

bl-plugins/api/plugin.php
=> add missing api endpoint (GET) /api/pages

bl-languages/installer/nl_NL.php
=> Dutch for installer

bl-kernel/admin/controllers/edit-user.php
Display the user name in the title of page `/admin/edit-user/$username`, in the same way as it's implemented for `/admin/edit-category/$category`.
=> Display the user name in the title of page /admin/edit-user/$username

bl-kernel/login.class.php
At this line, the  `$user ` is a `array` and not the User Object `User`.
=> Fix handling array as object

bl-kernel/helpers/simple-image.class.php, bl-kernel/page.class.php
Instead of adding a new dynamic property to the DateInterval-Object, a new var is created which stores the weeks. Inside the `foreach` a handler is created by checking, if the current `$key` is `w` for weeks.
=> Fix Deprecated message

bl-themes/popeye/php/footer.php
To validate your website within your Mastodon profile, you have to have a link to your Mastodon profile in your website with the attribute rel=me in the tag. The Popeye theme has an auto link to Mastodon but it does not include the rel=me attribute. This pull request adds the rel=me link to the Mastodon social link only.
=> Popeye mastadon

install.php
=> Use checkbox instead of text [Installer]

bl-kernel/functions.php, bl-themes/blogx/php/home.php, bl-themes/blogx/php/page.php, bl-themes/popeye/php/page.php
=> Minor improvements in default themes

bl-plugins/alternative/languages/ru.json
Added russian translation for this plugin
=> Created ru.json

bl-themes/alternative/php/footer.php, bl-themes/blogx/php/footer.php
This earlier change https://github.com/bludit/bludit/commit/2ab78beb8b748e877b828aa9be584052e7d2d019 added spurious `span` closing tags.
=> Remove spurious </span> from theme footer

bl-kernel/admin/views/dashboard.php
This earlier change https://github.com/bludit/bludit/commit/bfabd248ac87d549bbee78c5442bce222c36eb13#diff-a8894df04938191b7d63d86421f3e8abf2d90d1ab7b18d4c771eeaa37d890516  didn't handle hour values of 6, 12 or 18 correctly. For times with those hours the code falls through to the "good night" message.
=> Welcome message displays "good night" in the afternoon

bl-kernel/pages.class.php, bl-kernel/pagex.class.php
See comments in commits. Changes requires at least PHP 7.0
=> Fix 2 deprecated messages
