bludit/bludit

bl-plugins/tags/languages/en_US.json
bl-plugins/tags/plugin.php

Enable sorting of the tags shown when using the tags plugin. Options
for sorting are "Alphabetical", "Count" and "Date". Date is the
default as it is the current way of sorting.
Also, use PHP function ucfirst to beautify the tags list.
Translations added for en_US only.

[Tags Plugin] Enable sorting & beautify with ucfirst()

---

bl-plugins/opengraph/plugin.php

`$og['image']` **is** `false` in this segment. So, no reason to use it as suffix to the image url.

patch OpenGraph plugin

---

bl-kernel/dblanguage.class.php
bl-plugins/tags/languages/de_DE.json
bl-plugins/tags/languages/en_US.json
bl-plugins/tags/plugin.php

Instead of the default string $Language->get($string) previously
returned an empty string, breaking the default translation behaviour of
all default plugins except the tags plugin (which was fixed in the
course of the change).

Fixed translation and updated tags plugin

---

bl-kernel/ajax/uploader.php

init.php sets up different variables than the one used in here. ( 'IMG_' is missing )

fix typo in uploader.php

---

bl-plugins/rss/plugin.php
bl-plugins/sitemap/plugin.php

If running Bludit inside same PHP/FastCGI instance with other scripts calling libxml_disable_entity_loader(true), call to DOMDocument::load fails with "I/O warning : failed to load external entity". See [here](https://bugs.php.net/bug.php?id=62577) for details in PHP bugtracker. Added suggested workaround to sitemap and RSS plugins.

Patch for "failed to load external entity" errors in DOMDocument::load calls

---

bl-kernel/admin/themes/default/css/default.css
bl-kernel/admin/views/plugins.php
bl-kernel/admin/views/themes.php

Originally the Plugins page looked like this. It is difficult to see which plugins are active or have settings pages, as you have to read the words.
I've changed to use icons instead, which gives a clean look and it's easy now to identify the plugins that are active and have settings. The words are still used, as tooltips that appear when you hover on the icons.
Similar changes applied to Themes page as well. Kindly view the commit messages themselves for more details.
**Side note:** In a separate commit, I also corrected a spelling mistake in a link attribute name which caused the author links to open in the same tab instead of a new tab.

Icons in the Plugins and Themes pages

---

bl-kernel/abstract/content.class.php
bl-kernel/dbposts.class.php

Returns:
(a) short version : "1 hour ago"
(b) long version  : "1 hour, 1 minute, 1 second ago"
Also diff shows the whole file changed, probably because I copy pasted from another folder into my fork. Only one function was added which is `relativeTime()`.

Get relative time from content & Keep UUID

---

bl-kernel/dbpages.class.php
bl-kernel/helpers/text.class.php

A new function is created to achieve this, Text::truncate
which is based on Text::cut from the text.class.php helper.
Limit is set to 60 characters.
Example A:
Content has over 60 characters.
Title = First 60 characters + remaining characters of the last word + '...'
Example B:
Content has less than or equal to 60 characters
Title = All.
Example C:
Content only has one word but is over 60 characters.
Title = First 60 characters + '...'
Why B and C differ from each other?
Because we do not want the whole that one weird word
with over 60 characters to make its way to the title.
It's probably unrealistic, the code can be much cleaner
with B and C combined.
Feel free to discuss.

Generate title and description (if empty) from the content.

---

bl-plugins/robots/plugin.php

According to https://developers.google.com/search/reference/robots_meta_tag, http://www.robotstxt.org/meta.html and https://www.webmasterworld.com/forum93/669.htm using only a space between the values probably isn't the proper syntax and could ignore all values (perhaps that explains why Google ignored my `noindex nofollow`).

Use comma for imploding robots meta tag

---

bl-kernel/admin/themes/booty/html/sidebar.php

Hellow,
as mentioned in [this Forum Post](https://forum.bludit.org/viewtopic.php?f=20&t=1426) (written in German), it would be really awesome to "show" custom admin sidebar links for editors too. So plugins, which handles any content related stuff, would be also available for non-adminstrators.
Thanks.
Sincerely,
Sam.

Enable adminSidebar() also for Editors

---

bl-kernel/security.class.php

In `bl-kernel/security.class.php`, there is some code that will check the number of incorrect login attempts made by a host. If the host makes 10 incorrect attempts, they will be temporarily blocked in order to mitigate brute force attempts.
Due to the way the IP address detection is handled, the mechanism can be completely bypassed. The `X-Forwarded-For` and `Client-IP` headers are both checked for (presumably in order to try and detect the IP address of people behind proxies). Unfortunately, both of these headers are easily spoofed, and for an attacker that is running an automated brute force, this will make the process significantly easier than say switching between VPNs as each address gets banned.
I have included a proof of concept demo below in which you can see a total of 51 …

Remove use of headers that can be used to bypass anti-brute force controls

---

bl-kernel/helpers/theme.class.php

This is a follow up to a previous PR. The `async` attribute can cause issues with some js files. For instance I added the [lozad.js](https://github.com/ApoorvSaxena/lozad.js) for lazy loading and included it via my theme. However, with the current automatic inclusion of `async` things didn't work. 
So this update allows Theme developers to prevent the `async` attribute by passing in `null`.
Example: 
```
<?php echo Theme::javascript('js/lozad.min.js', DOMAIN_THEME, null); ?>
```
If the Theme developer doesn't include `null` the default will be to use `async`.

Allow passing in attributes for Theme js files

---

bl-kernel/helpers/filesystem.class.php

Hellow,
the Backup plugin doesn't work properly as described on this [forum post](https://forum.bludit.org/viewtopic.php?f=20&p=8153#p8153) (written in German).
The issue is mainly located on the filesystem helper file starting at line 177
```php
if (is_dir($file)) {
$zip->addEmptyDir(str_replace($source, '', $file));
} elseif (is_file($file)) {
$zip->addFromString(str_replace($source, '', $file), file_get_contents($file));
}
```
The internal ZIP Path (set as first parameter on both functions) starts with a (back-) slash, if `$source` doesn't end with the respective directory separator. 
This leads to an "invalid" ZIP path structure (okay, it is not invalid but everything gets written in an invisible unnamed directory). That's also the reason why the backup plugin doesn't work, because …

[BUGFIX] ZIP Paths may starts with an (back-) slash

---

bl-kernel/admin/views/edit-content.php

Hellow,
since you replaced the `autoComplete` library with `select2` in Bludit v3.10.0 (see [commit#e153a20](https://github.com/bludit/bludit/commit/582dd2624396ff8989713688ca27ab36b992a92f) and [commit#b86f317](https://github.com/bludit/bludit/commit/c5977fc0cbc85116c1fc40d71bc2dca04845ae43)) the following lines are no longer required. In addition, these also cause an error message in the Browser JavaScript console:
`TypeError: $(...).autoComplete is not a function`
Sincerely,
Sam.

[BUGFIX] Remove deprecated autoComplete Function

---

bl-plugins/search/plugin.php

This Pull Request just adds an if-condition to check if `$itemsPerPage` is set to "All Content" (0 or lower) or not, to fix the related issue.

Bugfix: Search Plugin will not work if itemsPerPage is set to "All Content"

---

bl-kernel/admin/themes/booty/index.php

Defaulting to async is leading to buggy behaviour https://github.com/bludit/bludit/pull/1172/files
Affects Google Chrome. Maybe we should not `async` by default here - https://github.com/bludit/bludit/blob/master/bl-kernel/helpers/theme.class.php

Remove async from select2

---

bl-kernel/admin/themes/booty/index.php
bl-kernel/boot/admin.php

Hellow,
it would be really awesome if plugins are able to add custom admin pages, instead of just using the `form()` method. This could be used to develop far more extensive plugins in a defined way, without "hacking" into the booty's admin theme [as described on #1057](https://github.com/bludit/bludit/issues/1057#issuecomment-507933944).
With this pull request, the main Plugin class just needs to define the `adminController()` and `adminView()` methods to add another admin page. For example:
```php
<?php
class SkeletonPlugin extends Plugin
{
public function adminController()
{
global $layout;
// Set custom tite
$layout["title"] = "Skeleton Plugin | Bludit";
}
public function adminView()
{
// Return admin page content
return "test";
}
}
```
The page is available at …

Add custom admin pages

---

bl-kernel/helpers/cookie.class.php
bl-kernel/helpers/session.class.php

Hellow,
the Cookie and especially the Session helper classes should also provide a `remove()` function. Not only to provide the full functionality, but also because the Session prefix the keys with `s_`.
Thanks.
Sincerely,
Sam.

Allow removing Session & Cookie Entries

---

bl-kernel/ajax/logo-upload.php
bl-kernel/ajax/profile-picture-upload.php
bl-kernel/ajax/upload-images.php
bl-kernel/boot/variables.php

Hellow,
this pull request adds a File MIME Type check to all 3 AJAX requests to prevent file injection as described in #1218 and #1212. 
- `logo-upload.php`
- `profile-picture-upload.php`
- `upload-images.php`
It also adds a new GLOBAL variable called `ALLOWED_IMG_MIMETYPES` with the respective allowed types: `image/gif`, `image/png`, `image/jpeg` and `image/svg+xml`.
~ Sam.

MIME Type Check for Issue #1218 and #1212

---

bl-kernel/functions.php
bl-kernel/helpers/theme.class.php

Hellow,
after playing with the `afterPage*` plugin hooks, I figured out that it is not possible to get the key of a new created, modified or deleted page. I played a bit around and found the following solution, which not only helps to work with the `afterPage*` hooks but also extends the plugin hook API in general.
Now you can pass additional arguments, and use them within the respective function, something like...
```php
<?php
class MyPlugin extends Plugin {
public function afterPageCreate($key) {
$page = new Page($key);
// Work with the Page Object
}
}
```
Would be really cool to have.
~ Sam.

Extend plugins hook

---

bl-kernel/helpers/text.class.php

Hellow,
this pull request allows using dots in the `Text` helper method `cleanUrl()`, this would also allow us to use dots on slugs and page key names. 
- The page author is not restricted and can force dots if needed
- For example if he reviews domains - `https://www.example.com/review/google.com`
- For example if a product contains a styling - `https://www.codeblu.dev/plugins/tail.writer`
- For example if a dot would look better - `https://www.example.com/talking-about.dots`
- The page author can 'pretend' static .html pages using `.html`
- He should try to avoid `index.php` or `install.php`, which cannot happen unintentionally ;)
If the user doesn't want to use dots, or if the admin wants to avoid them - for example on a Bludit website with multiple authors - he can still enable the …

Allow dots in URL

---

bl-kernel/admin/themes/booty/html/navbar.php

Removed categories, users, settings, plugins, themes, about from mobile navebar. Kept all the adminSidebars for admin only.

Removing unwanted mobile menu option for editor and author

---

bl-kernel/admin/themes/booty/html/media.php
bl-kernel/admin/views/edit-content.php
bl-kernel/admin/views/new-content.php
bl-languages/de_AT.json
bl-languages/de_CH.json
bl-languages/de_DE.json
bl-languages/en.json
bl-plugins/tinymce/plugin.php

When inserting an image into a page, the image will be inserted using the original size. This slows down the page load if many large images are inserted.
Two new options allow the user to insert thumbnails instead, either with a link or without a link to the original image.
German translations are included.

feat: Allow images to be inserted as thumbnails or as linked thumbnails

---

bl-languages/de_AT.json
bl-languages/de_CH.json
bl-languages/de_DE.json

This pull request will just fix the 'mitatbeiter' typo in german local files

fix 'mitatbeiter' typo in german (DE,AT & CH) locale files

---

bl-kernel/helpers/paginator.class.php

This commit provides minor improvements to the helper class Paginator in bl-kernel. The goal of this commit is to make the bootstrap pagination generated by bootstrapHTML() actually usable - since not even the two themes provided by default are using it.
Fixes:
- variable name typo fixed in Paginator::bootstrapHTML() show_previous
- removed page parameter from URL generated by Paginator::numberUrl() when pageNumber = 1. This is to prevent generating duplicate pages with different URL and negative impact to SEO since pageNumber = 1 is the default option in url.class.php.
- Some elements of the bootstrap pagination were missing necessary CSS classes.
Improvements
- added handling of the button text overrides to Paginator::bootstrapHTML() - the parameters were not used.
- added handling of …

V4.0 bootstrap pagination

---

bl-languages/nl_NL.json

Missing comma and it shows the errors at installation page,
It seems some people also face [this issue here](https://forum.bludit.org/viewtopic.php?t=2145).
Clone this repo and try to install it.
However, the one from Bludit domain is working fine `https://www.bludit.com/releases/bludit-3-13-1.zip`.
Tested on MacOS, Nginx.

Missing comma - it shows the errors at installation page

---

bl-plugins/version/plugin.php

Update badge css to math bootstrap v5.1.3 as used in Bludit 4.x. css class names for badges has changed since boostrap 5.x from bagdewarning to bg-warning and badge-pill to rounded-pill. This allows to show correct badge in admin sidebar (menu)

version badge on admin sidebar

---

bl-kernel/admin/views/editor.php

Commit adds support for adding a list with commas to the tag field. The JavaScript splits the commas in the string and adds the trimmed text to the tag list (if already exists, select the tag).

Comma Seperated Tags List Walker Feature

---

bl-kernel/pages.class.php

The upload directory for a page is named by UUID not by the page name.
Fixes #1545

Use the page UUID to identify the upload directory when deleting a page
